name: Run Selenium Tests (CI/CD)

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Setup Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 3. Install Google Chrome
      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" \
            | sudo tee /etc/apt/sources.list.d/google.list
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      # 4. Install ChromeDriver
      - name: Install ChromeDriver
        uses: nanasess/setup-chromedriver@v2

      # 5. Install SQL Server ODBC + pyodbc
      - name: Install ODBC + pyodbc
        run: |
          sudo apt-get update

          sudo apt-get install -y curl gnupg
          curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
          curl https://packages.microsoft.com/config/ubuntu/22.04/prod.list \
            | sudo tee /etc/apt/sources.list.d/mssql-release.list

          sudo apt-get update
          sudo ACCEPT_EULA=Y apt-get install -y msodbcsql18 mssql-tools18 unixodbc-dev

          python -m pip install --upgrade pip
          pip install pyodbc

      # 6. Install project dependencies
      - name: Install Python dependencies
        run: pip install -r requirements.txt

      # 7. Create folder
      - name: Create reports folders
        run: |
          mkdir -p reports
          mkdir -p screenshots

      # 8. Run tests
      - name: Run Pytest
        run: pytest --disable-warnings -v

            # 9. Convert Excel -> HTML
      - name: Convert Excel report to HTML
        run: |
          pip install pandas openpyxl
          python << 'EOF'
          import pandas as pd
          import glob
          import os

          os.makedirs("reports", exist_ok=True)

          files = glob.glob("reports/*.xlsx")
          if not files:
              print("⚠ No Excel reports found!")
          else:
              for f in files:
                  df = pd.read_excel(f)
                  html_file = f.replace(".xlsx", ".html")
                  df.to_html(html_file, index=False)
                  print("Converted:", f, "->", html_file)
          EOF


      # 10. Upload artifacts
      - name: Upload test results and screenshots
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            reports/*.xlsx
            reports/*.html
            screenshots/
